version: '3.8'

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    networks:
      - mynetwork

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 16202620
      MYSQL_DATABASE: mysourcing
      MYSQL_USER: japheth
      MYSQL_PASSWORD: 16202620
    ports:
      - "3306:3306"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
